# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dugompertz <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_ugomquantreg_cpp_dugompertz', PACKAGE = 'ugomquantreg', x, mu, theta, tau, logprob)
}

cpp_pugompertz <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_ugomquantreg_cpp_pugompertz', PACKAGE = 'ugomquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qugompertz <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_ugomquantreg_cpp_qugompertz', PACKAGE = 'ugomquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_dmu <- function(x, mu, sigma, nu) {
    .Call('_ugomquantreg_cpp_dmu', PACKAGE = 'ugomquantreg', x, mu, sigma, nu)
}

